AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Real-Time Inventory SAM template for the AWS Collector

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  AWSCollectorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        InstanceTerminated:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail:
                state:
                  - terminated
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        EntryPoints:
          - index.ts

Outputs:
  AWSCollectorFunction:
    Description: 'AWS Collector Lambda Function ARN'
    Value: !GetAtt AWSCollectorFunction.Arn
