version: '3.8'

services:
  postgres:
    image: docker.io/bitnami/postgresql:15
    environment:
      - POSTGRESQL_DATABASE=neobank
    env_file:
      - ./postgres/.env
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/bitnami/postgresql'
  neo4j:
    image: docker.io/bitnami/neo4j:5
    env_file:
      - ./neo4j/.env
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - 'neo4j_data:/bitnami'

volumes:
  postgres_data:
    driver: local
  neo4j_data:
    driver: local
