version: '3'

services:
  namenode:
    image: hadoop-namenode
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode_1:
    image: hadoop-datanode
    container_name: datanode_1
    restart: always
    volumes:
      - hadoop_datanode_1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: 'namenode:9870'
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode

  datanode_2:
    image: hadoop-datanode
    container_name: datanode_2
    restart: always
    volumes:
      - hadoop_datanode_2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: 'namenode:9870'
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode

  datanode_3:
    image: hadoop-datanode
    container_name: datanode_3
    restart: always
    volumes:
      - hadoop_datanode_3:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: 'namenode:9870'
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode

  resourcemanager:
    image: hadoop-resourcemanager
    container_name: resourcemanager
    restart: always
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: 'namenode:9000 namenode:9870 datanode_1:9864 datanode_2:9864 datanode_3:9864'
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: hadoop-nodemanager
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: 'namenode:9000 namenode:9870 datanode_1:9864 datanode_2:9864 datanode_3:9864 resourcemanager:8088'
    env_file:
      - ./hadoop.env

  historyserver:
    image: hadoop-historyserver
    container_name: historyserver
    restart: always
    ports:
      - 8188:8188
    environment:
      SERVICE_PRECONDITION: 'namenode:9000 namenode:9870 datanode_1:9864 datanode_2:9864 datanode_3:9864 resourcemanager:8088'
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env

volumes:
  hadoop_namenode:
  hadoop_datanode_1:
  hadoop_datanode_2:
  hadoop_datanode_3:
  hadoop_historyserver:
